#!/bin/sh

# autostart programs
$HOME/.config/bspwm/autostart.sh

# bspwm configuration
#bspc config border_radius       8 
bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          0
bspc config bottom_padding       30
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# bspwm coloring
bspc config normal_border_color 	"#1e1e2e"
bspc config focused_border_color 	"#89b4fa"

# single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9

# fullscreen applications
#bspc rule -a inkscape state=fullscreen
#bspc rule -a Spotify state=fullscreen
#bspc rule -a Vlc state=fullscreen
#bspc rule -a VirtualBox Manager state=fullscreen
#bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

# floating applications
bspc rule -a Arandr state=floating
bspc rule -a Archlinux-tweak-tool.py state=floating
bspc rule -a Arcolinux-welcome-app.py state=floating
bspc rule -a Arcolinux-calamares-tool.py state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
bspc rule -a Qalculate-gtk state=floating
#bspc rule -a Gpick state=floating sticky=on
#bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#bspc rule -a Pavucontrol state=floating sticky=on
#bspc rule -a Peek state=floating
#bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating
#bspc rule -a Stacer state=floating
#bspc rule -a Xfce4-appfinder state=floating sticky=on
bspc rule -a Xfce4-terminal state=floating
bspc rule -a Tk state=floating
bspc rule -a Catppuccinifier-gui state=floating

# tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

